channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.3
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.1
  - lz4==4.4.4
  - numpy==2.3.5
  - pandas==2.3.3
  - psutil==6.1.1
  - scikit-learn==1.6.0
  - scipy==1.15.0
name: mlflow-env